"""new Item and StoreItemRelation tables created

Revision ID: dad5aa000208
Revises: fe6ece521913
Create Date: 2025-04-27 23:13:11.486695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad5aa000208'
down_revision = 'fe6ece521913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_image', sa.LargeBinary(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('store_item_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['item.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('store_location_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('store_description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('store_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('store_location_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    op.drop_table('store_item_relation')
    op.drop_table('item')
    # ### end Alembic commands ###
